### ISSUE TITLE
Thanks for update DB, question

### ISSUE THREAD

**Issue by seega** [SayWhat69/Plutus#10]
Is it possible to use as a database text file with a list of addresses?

**Comment by seega** [comment]
i found resolve

> import pickle
> PIK = "00.pickle"
> 
> with open("bitcoinfile.txt") as file_in: # one P2PKH bitcoin address per line i.e starting with 1 dnt load other addresses 
>     data = set()
>     for line in file_in:
>         dline = line.rstrip("\n")
>         data.add(dline)
> with open(PIK, "wb") as f:
>     pickle.dump(data, f)

**Comment by cryptoforum8** [comment]
> я нашел решение
> 
> > импортировать рассол 
> > PIK = "00.pickle"
> > с open ("bitcoinfile.txt") как file_in: # один биткойн-адрес P2PKH на строку, т.е. начиная с 1 dnt загружать другие адреса 
> > data = set () 
> > для строки в file_in: 
> > dline = line.rstrip ("\ n") 
> > data. добавить (dline) 
> > с open (PIK, "wb") как f: 
> > pickle.dump (data, f)

работает? все норм?

**Comment by seega** [comment]
> > я нашел решение
> > > импортировать рассол
> > > PIK = "00.pickle"
> > > с open ("bitcoinfile.txt") как file_in: # один биткойн-адрес P2PKH на строку, т.е. начиная с 1 dnt загружать другие адреса
> > > data = set ()
> > > для строки в file_in:
> > > dline = line.rstrip ("\ n")
> > > data. добавить (dline)
> > > с open (PIK, "wb") как f:
> > > pickle.dump (data, f)
> 
> работает? все норм?

работает, только если ты код будешь через переводчик копировать, то работать не будет
