### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by telix5000** [SayWhat69/Plutus#2]
What is the code being used to extract the newest updates for the database? I noticed the OP of the first iteration didn't include really any workflow to generate our own, so if you don't mind, could you share?

**Comment by ZaranTheWise** [comment]
https://github.com/Isaacdelly/Plutus/issues/151#issuecomment-572892817

For a much bigger convo on the topic, check out the whole issue

**Comment by telix5000** [comment]
Perfect! Thank you!
