### ISSUE TITLE
killed? 

### ISSUE THREAD

**Issue by ghost** [SayWhat69/Plutus#4]
```
$ python3 plutus.py                                                
reading database: 33/34zsh: killed     python3 plutus.py

reading database: 33/34^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[B^[[B^[[B^[[A^[[A^[[A^[[B^[[B^[[B^[[B^[[B^[[Bzsh: killed     python3 plutus.py

```

**Comment by fluffybird2323** [comment]
i couldn't replicate this :/

**Comment by fluffybird2323** [comment]
Try the original plutus repository

**Comment by SayWhat69** [comment]
Looks like your Computer ran out of memory. How much RAM do you have?

**Comment by armor1991** [comment]
i have same problem here man. Just using vm with 4 gb ram here.isnt it enough?

**Comment by armor1991** [comment]
orginal plutus works fine btw

**Comment by SayWhat69** [comment]
> i have same problem here man. Just using vm with 4 gb ram here.isnt it enough?

you need to have enough RAM to load the whole database.

**Comment by armor1991** [comment]
> > i have same problem here man. Just using vm with 4 gb ram here.isnt it enough?
> 
> you need to have enough RAM to load the whole database.

i see ty. do you also know why the all private keys starts with 1? it doesnt seemed so random to me?

**Comment by SayWhat69** [comment]
> > > i have same problem here man. Just using vm with 4 gb ram here.isnt it enough?
> > 
> > 
> > you need to have enough RAM to load the whole database.
> 
> i see ty. do you also know why the all private keys starts with 1? it doesnt seemed so random to me?

uhm you should ask that in the original repo ;)
