### ISSUE TITLE
Error after updating database

### ISSUE THREAD

**Issue by vladsevsk777** [SayWhat69/Plutus#5]
With the database "MAR_23_2019" works without problems. Copied the new "MAR_15_2021" to the database folder, changed it in the file DATABASE = r'dbase/MAR_15_2021/' - returns an error.

![image](https://user-images.githubusercontent.com/84088755/118438463-1a51b980-b6ed-11eb-83d4-97b5b6de2f0a.png)

Please help me understand.

**Comment by SayWhat69** [comment]
You need to use my whole repo, not just the database.
